
export type Language = 'pt-BR' | 'en-US';
export type Unit = 'metric' | 'imperial';

export const translations = {
  'pt-BR': {
    home: 'Home',
    history: 'Análises',
    details: 'Detalhes',
    settings: 'Ajustes',
    greeting: 'Olá',
    ready: 'Acompanhe suas refeições de hoje',
    consumed_today: 'Consumido hoje',
    analyze_meal: 'Analisar refeição',
    recent_uploads: 'Uploads recentes',
    view_all: 'Ver todos',
    no_meals: 'Nenhuma refeição registrada ainda.',
    protein: 'Proteínas',
    carbs: 'Carboidratos',
    fat: 'Gorduras',
    fiber: 'Fibras',
    calories: 'Calorias',
    history_title: 'Histórico',
    no_records: 'Nenhum registro encontrado.',
    energy: 'Energia Total',
    ingredients: 'Ingredientes Estimados',
    observation: 'Observação da IA',
    approx_values: 'Valores aproximados com base em análise por IA',
    config_title: 'Configurações',
    config_subtitle: 'Gerencie suas preferências.',
    unit_measure: 'Unidade de Medida',
    preferences: 'Preferências',
    language: 'Idioma',
    general: 'Geral',
    terms: 'Termos de Uso',
    privacy: 'Privacidade',
    support: 'Suporte',
    metric: 'Métrico (g, kg)',
    imperial: 'Imperial (oz, lb)',
    select_language: 'Selecionar Idioma',
    select_unit: 'Unidade de Medida',
    analyzing: 'Analisando...',
    take_photo: 'Tirar foto',
    gallery: 'Galeria',
    back: 'Voltar',
    last_update: 'Última atualização',
    terms_title: 'TERMOS DE USO',
    privacy_title: 'POLÍTICA DE PRIVACIDADE',
    support_title: 'Central de Suporte',
    support_intro: 'Estamos aqui para ajudar você a aproveitar ao máximo o MacroPlan.',
    faq_title: 'Perguntas Frequentes',
    contact_title: 'Entre em Contato',
    faq_1_q: 'Como funciona a análise nutricional?',
    faq_1_a: 'O MacroPlan usa inteligência artificial avançada para identificar os alimentos na imagem e estimar seus valores nutricionais.',
    faq_2_q: 'Os valores são precisos?',
    faq_2_a: 'Os valores são aproximados e baseados em análise por IA. Para maior precisão, consulte um nutricionista.',
    appearance: 'Aparência',
    theme: 'Tema',
    theme_light: 'Tema Claro',
    theme_dark: 'Tema Escuro',
    theme_system: 'Seguir sistema',
    select_appearance: 'Escolher Aparência',
    health_score: 'Health Score',
    score_poor: 'Pouco equilibrado',
    score_regular: 'Regular',
    score_good: 'Bom',
    score_very_good: 'Muito bom',
    avg_health: 'Média de Saúde',
    breakfast: 'Café da manhã',
    lunch: 'Almoço',
    dinner: 'Jantar',
    snack: 'Lanche',
    supper: 'Ceia',
    identified_foods: 'Alimentos identificados',
    user_adjusted: 'Ajustado',
    daily_goal: 'Meta Calórica',
    goal_range_error: 'Insira um valor entre 1000 e 4500 kcal',
    save: 'Salvar',
    clear_data: 'Limpar dados',
    clear_today: 'Limpar hoje',
    clear_all: 'Limpar tudo',
    confirm_clear_title: 'Limpar Histórico',
    confirm_clear_desc: 'Tem certeza que deseja apagar os registros?',
    action_irreversible: 'Essa ação não pode ser desfeita.',
    cancel: 'Cancelar',
    clear: 'Limpar',
    camera_access_denied: 'Acesso à câmera negado',
    confirm_analysis: 'Confirmar Alimentos',
    confirm_save: 'Salvar Refeição',
    adjust_grams: 'Ajustar Quantidade',
    grams: 'Gramas',
    reset_analysis: 'Redefinir análise',
    confirm_reset: 'Deseja restaurar a análise original da IA?',
    restore: 'Restaurar',
    removed_items: 'Removidos',
    delete_meal_confirm: 'Deseja apagar esta análise?',
    delete_meal_desc: 'Esta refeição será removida permanentemente.',
    delete_action: 'Apagar',
    meal_name_placeholder: 'Nome da refeição (ex: Almoço)',
    meal_label: 'Nome da refeição',
    quick_select: 'Seleção rápida',
    app_version: 'MacroPlan — Versão 1.0',
    capture: 'Capturar',
    switch_camera: 'Inverter Câmera',
    edit_item: 'Editar Ingrediente',
    add_item: 'Adicionar Ingrediente',
    add_as_new: 'Adicionar como novo ingrediente',
    search_food: 'Buscar alimento...',
    item_name: 'Nome do alimento',
    item_amount: 'Quantidade',
    item_updated: 'Ingrediente atualizado',
    item_added: 'Ingrediente adicionado',
    item_removed: 'Ingrediente removido',
    analysis_reset: 'Ingredientes restaurados',
    manual_entry: 'Entrada manual',
    ai_estimating: 'IA estimando valores...'
  },
  'en-US': {
    home: 'Home',
    history: 'History',
    details: 'Details',
    settings: 'Settings',
    greeting: 'Hello',
    ready: 'Track your meal for today',
    consumed_today: 'Consumed today',
    analyze_meal: 'Analyze meal',
    recent_uploads: 'Recent uploads',
    view_all: 'View all',
    no_meals: 'No meals recorded yet.',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    fiber: 'Fiber',
    calories: 'Calories',
    history_title: 'History',
    no_records: 'No records found.',
    energy: 'Total Energy',
    ingredients: 'Estimated Ingredients',
    observation: 'AI Observation',
    approx_values: 'Approximate values based on AI analysis',
    config_title: 'Settings',
    config_subtitle: 'Manage your preferences.',
    unit_measure: 'Unit of Measure',
    preferences: 'Preferences',
    language: 'Language',
    general: 'General',
    terms: 'Terms of Use',
    privacy: 'Privacy Policy',
    support: 'Support',
    metric: 'Metric (g, kg)',
    imperial: 'Imperial (oz, lb)',
    analyzing: 'Analyzing...',
    take_photo: 'Take photo',
    gallery: 'Gallery',
    back: 'Back',
    last_update: 'Last update',
    terms_title: 'TERMS OF USE',
    privacy_title: 'PRIVACY POLICY',
    support_title: 'Support Center',
    support_intro: 'We are here to help you get the most out of MacroPlan.',
    faq_title: 'Frequently Asked Questions',
    contact_title: 'Get in Touch',
    faq_1_q: 'How does nutritional analysis work?',
    faq_1_a: 'MacroPlan uses advanced AI to identify foods in images and estimate nutritional values.',
    faq_2_q: 'Are the values accurate?',
    faq_2_a: 'Values are approximate. For greater accuracy, consult a nutritionist.',
    appearance: 'Appearance',
    theme: 'Theme',
    theme_light: 'Light Theme',
    theme_dark: 'Dark Theme',
    theme_system: 'System default',
    select_appearance: 'Choose Appearance',
    health_score: 'Health Score',
    score_poor: 'Unbalanced',
    score_regular: 'Fair',
    score_good: 'Good',
    score_very_good: 'Excellent',
    avg_health: 'Health Average',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    snack: 'Snack',
    supper: 'Supper',
    identified_foods: 'Identified foods',
    user_adjusted: 'Adjusted',
    daily_goal: 'Daily Goal',
    goal_range_error: 'Enter a value between 1000 and 4500 kcal',
    save: 'Save',
    clear_data: 'Clear data',
    clear_today: 'Clear today',
    clear_all: 'Clear all',
    confirm_clear_title: 'Clear History',
    confirm_clear_desc: 'Are you sure you want to delete the records?',
    action_irreversible: 'This action cannot be undone.',
    cancel: 'Cancel',
    clear: 'Clear',
    camera_access_denied: 'Camera access denied',
    confirm_analysis: 'Confirm Foods',
    confirm_save: 'Save Meal',
    adjust_grams: 'Adjust Amount',
    grams: 'Grams',
    reset_analysis: 'Reset analysis',
    confirm_reset: 'Do you want to restore the original AI analysis?',
    restore: 'Restore',
    removed_items: 'Removed',
    delete_meal_confirm: 'Delete this analysis?',
    delete_meal_desc: 'This meal will be permanently removed.',
    delete_action: 'Delete',
    meal_name_placeholder: 'Meal name (e.g., Lunch)',
    meal_label: 'Meal name',
    quick_select: 'Quick select',
    app_version: 'MacroPlan — Version 1.0',
    capture: 'Capture',
    switch_camera: 'Switch Camera',
    edit_item: 'Edit Ingredient',
    add_item: 'Add Ingredient',
    add_as_new: 'Add as new ingredient',
    search_food: 'Search food...',
    item_name: 'Food name',
    item_amount: 'Amount',
    item_updated: 'Ingredient updated',
    item_added: 'Ingredient added',
    item_removed: 'Ingredient removed',
    analysis_reset: 'Analysis restored',
    manual_entry: 'Manual entry',
    ai_estimating: 'AI estimating values...'
  }
};

export const formatNumber = (val: number, lang: Language = 'pt-BR'): string => {
  if (Number.isInteger(val)) return val.toString();
  const formatted = val.toFixed(1);
  return lang === 'pt-BR' ? formatted.replace('.', ',') : formatted;
};

export const formatWeight = (grams: number, unit: Unit, lang: Language = 'pt-BR'): string => {
  if (unit === 'metric') return `${formatNumber(grams, lang)}g`;
  const oz = grams * 0.035274;
  return `${formatNumber(oz, lang)}oz`;
};
